### ISSUE TITLE
Fog URL sometimes gets set to empty region

### ISSUE THREAD

**Issue by jkeiser** [chef/chef-provisioning-fog#35]
A user encountered a situation where they used driver "fog:AWS" and had AWS_ACCESS_KEY_ID and AWS_SECRET_KEY set, as well as a ~/.aws/config with a default profile with no region.  They created a server and its driver_url got stashed as "fog:AWS:12471238123:"

Two problems:

- first, it's weird we didn't know the region and we probably should figure that out
- second, there's no reason we can't parse URLs like this.

**Comment by msonnabaum** [comment]
This bug also hit me pretty hard.

In my case, I don't have a ~/.aws/config, but I do have AWS_ACCESS_KEY_ID, AWS_SECRET_KEY, and AWS_DEFAULT_REGION set.

My nodes were created with an earlier version of chef-metal-fog (I believe 0.4), and they all have the region-less driver_url. I upgraded to chef-provisioning-fog 0.12 to fix another issue, and then ran into this.

I added some logging, and it appeared to hit this clause the first time, which correctly picked up my environment variables:

https://github.com/chef/chef-provisioning-fog/blob/4b3b904db94a4667ae422ba69bd1c633b1b6f3d4/lib/chef/provisioning/fog_driver/providers/aws.rb#L197

But then this method was executed a second time, which ended up on this clause:

https://github.com/chef/chef-provisioning-fog/blob/4b3b904db94a4667ae422ba69bd1c633b1b6f3d4/lib/chef/provisioning/fog_driver/providers/aws.rb#L194

Which led to the "No AWS profile specified!" error message.

By commenting that clause out, it fell through to the environment variable part, and assembled the correct driver_url, but then I ended up with an error about not being able to move the nodes because the driver_urls were different.

I ultimately had to fix this by manually editing the node's driver_urls to include the region, and then it worked fine.

Hoping this provides some additional info on the bug or if nothing else helps the next person.
